@baseUrl = http://localhost:8100

### LOGIN ADMIN USER 1 ###
# @name admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

@adminAccess_token = {{admin.response.body.data.access_token}}
@adminRefresh_token = {{admin.response.body.data.refresh_token}}


### CREATE MANAGER USER 2 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Michael Anderson",
    "email": "michael.anderson@example.com",
    "password": "password1234",
    "roleIds": [4]  
}


## CREATE SUPPORT USER 3 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Claire Dupont",
    "email": "claire.dupont@example.com",
    "password": "password1234",
    "roleIds": [3]
}


### CREATE SUPPORT USER 4 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Julien Morel",
    "email": "julien.morel@example.com",
    "password": "password1234",
    "roleIds": [3]
}

### CREATE SUPPORT USER 5 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Amélie Rousseau",
    "email": "amelie.rousseau@example.com",
    "password": "password1234",
    "roleIds": [3]
}




### CREATE USER 6 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Emma Johnson",
    "email": "emma.johnson@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 7 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Daniel Martin",
    "email": "daniel.martin@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 8 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Sophie Bernard",
    "email": "sophie.bernard@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 9 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Lucas Moreau",
    "email": "lucas.moreau@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 10 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Olivia Turner",
    "email": "olivia.turner@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 11 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Nathan Scott",
    "email": "nathan.scott@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 12 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Chloé Dubois",
    "email": "chloe.dubois@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 13 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Gabriel Lefèvre",
    "email": "gabriel.lefevre@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 14 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Isabelle Laurent",
    "email": "isabelle.laurent@example.com",
    "password": "password1234",
    "roleIds": [2]
}

### CREATE USER 15 ###
POST {{baseUrl}}/api/admin/users
Authorization: Bearer {{adminAccess_token}}
Content-Type: application/json

{
    "name": "Thomas Keller",
    "email": "thomas.keller@example.com",
    "password": "password1234",
    "roleIds": [2]
}
